apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
- ingress.yaml

namespace: echo

images:
- name: pedroschmid2311/echo
  newName: pedroschmid2311/echo
  newTag: 11604889df04a002953f1fc8d3d9c0e68cbc0ea9
