apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foo-bar
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: default
  source:
    repoURL: https://github.com/pedroschmid/minukube-argocd.git
    targetRevision: HEAD
    path: apps/foo-bar
  destination:
    server: https://kubernetes.default.svc
    namespace: foo-bar
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true