apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
  # annotations:
    # argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: default
  source:
    repoURL: https://charts.konghq.com
    targetRevision: "2.8.0"
    chart: kong
    helm:
      parameters:
      - name: "ingressController.installCRDs"
        value: "false"
        forceString: true # ensures that value is treated as a string
      values: |
        podAnnotations:
          prometheus.io/scrape: "true" # Ask Prometheus to scrape Kong pods for metrics
          prometheus.io/port: "8100"
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      # - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true